package parkinggarage;

import java.io.File;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author J-Tron
 * @version 1.0
 * 
 * This class represents all of the required code to make the GUI operational with the 
 * garage program. 
 */
public class MainWindow extends javax.swing.JFrame {
    //Instantiates a default combo box that will be populated with parking fee calculation startegy objects
    private DefaultComboBoxModel<ParkingFeeCalculationStrategy> strategies = new DefaultComboBoxModel<ParkingFeeCalculationStrategy>();
    //Holds the parking fee calculation strategy object selected
    private ParkingFeeCalculationStrategy strategy;
    //Holds the parking company name
    private String parkingCompanyName;
    //Holds the garage company object
    private ParkingGarageCompany garageCompany; 
    //Holds the company address
    private String companyAddress;
    //Holds the garage manager object
    private GarageManager garageManager;
    //Holds the checkout service object
    private ParkingCheckoutService checkoutService;
    //Global car park counter used to reference the car number
    private int parkCounter = 0;
    //Holds the receipt output strategy object
    private ReceiptOutputStrategy receiptOutput;
    //Address of Best Value Parking Garage Company
    private final String BEST_VALUE_ADDRESS = "453 W. Main St. Milwaukee, WI 53225";
    //Address of Thrifty Parking Garage Company
    private final String THRIFTY_ADDRESS = "7546 Lombardi Dr. Green Bay, WI 54975";
    //Invalid hours parked entry message
    private final String HOURS_PARKED_ERROR_MESSAGE = "Please Enter the number of hours parked";
    //Message giving the user a hint of acceptable number ranges
    private final String VALID_PARKING_HOURS_ERROR_MESSAGE = "Enter a valid number HINT(0.01 - 24.00)";
    private final int MIN_LENGTH = 0;
    private final int MIN_PARK_HOURS = 0;
    private final int MAX_PARK_HOURS = 24;
    
    /**
     * Creates new form MainWindow
     * Calls methods setting up the main GUI and enables or disables buttons 
     * according to what functionality is required at startup
     */
    
    public MainWindow() {
        initParkingCalulators();
        initComponents();
        btnChangeFeeCalculator.setEnabled(false);
        btnCheckoutCar.setEnabled(false);
        btnParkCar.setEnabled(false);
    }
    
    /**
     * This method adds the parking fee calculation strategy objects to the 
     * JComboBox on the main window GUI
     * 
     */
    private void initParkingCalulators(){
        ParkingFeeCalculationStrategy strategy1 = new BestValueFeeCalculator();
        strategies.addElement(strategy1);
        ParkingFeeCalculationStrategy strategy2 = new ThriftyFeeCalculator();
        strategies.addElement(strategy2);
    }
    
    /**
     * This method sets the selected components of the GUI JComboBoxes to the local
     * variables for manipulation. It also puts the appropriate company address into the 
     * local variable based upon the selection within a JComboBox.
     * 
     * Given the selected parameters through the GUI, a garage company is instantiated,
     * the garage company is then used as a parameter for the instantiation of a garage manager object.
     * Finally the garage manager object is used as a parameter for the instantiation of a checkout service
     * object.
     */
    private void ConfirmSelectedComponents(){
        
        strategy = (ParkingFeeCalculationStrategy)jComboBoxFeeCalculator.getSelectedItem();
        parkingCompanyName = (String)jComboBoxParkingGarageCompany.getSelectedItem();
        
        if(jComboBoxParkingGarageCompany.getSelectedIndex() == 0){
            companyAddress = BEST_VALUE_ADDRESS;
        }
        if(jComboBoxParkingGarageCompany.getSelectedIndex() == 1){
            companyAddress = THRIFTY_ADDRESS;
        }
        
        garageCompany = new ParkingGarageCompany(parkingCompanyName, strategy, companyAddress);
        garageManager = new GarageManager(garageCompany);
        checkoutService = new ParkingCheckoutService(garageManager);
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        lblFeeCalculatorHeading = new javax.swing.JLabel();
        jComboBoxParkingGarageCompany = new javax.swing.JComboBox();
        lblParkingGarageCompanyHeading = new javax.swing.JLabel();
        jComboBoxFeeCalculator = new JComboBox(strategies);
        btnSelectCompanyAndCalculator = new javax.swing.JButton();
        lblSelectedCalculator = new javax.swing.JLabel();
        lblParkCarsHeading = new javax.swing.JLabel();
        txtHoursParked = new javax.swing.JTextField();
        lblHoursParkedHeading = new javax.swing.JLabel();
        btnParkCar = new javax.swing.JButton();
        lblCarParkedStatus = new javax.swing.JLabel();
        btnCheckoutCar = new javax.swing.JButton();
        lblParkingFee = new javax.swing.JLabel();
        lblHoursParkedErrorMessage = new javax.swing.JLabel();
        lblSelectedGarage = new javax.swing.JLabel();
        btnChangeFeeCalculator = new javax.swing.JButton();
        lblChangeCalcInstruction = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnExitProgram = new javax.swing.JButton();

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Parking Garage Interface");
        setBackground(new java.awt.Color(204, 204, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblFeeCalculatorHeading.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblFeeCalculatorHeading.setText("Select Fee Calculator");

        jComboBoxParkingGarageCompany.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jComboBoxParkingGarageCompany.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Best Value Parking Garage", "Thrifty Parking Garage" }));

        lblParkingGarageCompanyHeading.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblParkingGarageCompanyHeading.setText("Select Parking Garage Company");

        jComboBoxFeeCalculator.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        btnSelectCompanyAndCalculator.setBackground(new java.awt.Color(0, 204, 51));
        btnSelectCompanyAndCalculator.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        btnSelectCompanyAndCalculator.setText("Confirm Selections");
        btnSelectCompanyAndCalculator.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSelectCompanyAndCalculator.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSelectCompanyAndCalculator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectCompanyAndCalculatorActionPerformed(evt);
            }
        });

        lblSelectedCalculator.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N

        lblParkCarsHeading.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblParkCarsHeading.setText("Park A Vehicle");
        lblParkCarsHeading.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 255), 3)));

        lblHoursParkedHeading.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblHoursParkedHeading.setText("Enter Number of Hours to park Vehicle");

        btnParkCar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnParkCar.setText("Park Car");
        btnParkCar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 51), new java.awt.Color(0, 204, 51), new java.awt.Color(0, 204, 0), new java.awt.Color(0, 204, 51)));
        btnParkCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParkCarActionPerformed(evt);
            }
        });

        lblCarParkedStatus.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblCarParkedStatus.setForeground(new java.awt.Color(0, 0, 204));

        btnCheckoutCar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCheckoutCar.setText("Checkout Car");
        btnCheckoutCar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 0, 0), new java.awt.Color(255, 0, 0), new java.awt.Color(255, 0, 0), new java.awt.Color(255, 0, 0)));
        btnCheckoutCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckoutCarActionPerformed(evt);
            }
        });

        lblParkingFee.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblParkingFee.setForeground(new java.awt.Color(0, 0, 204));

        lblHoursParkedErrorMessage.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblHoursParkedErrorMessage.setForeground(new java.awt.Color(255, 0, 0));
        lblHoursParkedErrorMessage.setToolTipText("");

        lblSelectedGarage.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N

        btnChangeFeeCalculator.setBackground(new java.awt.Color(0, 0, 153));
        btnChangeFeeCalculator.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnChangeFeeCalculator.setText("Change Fee Calculator");
        btnChangeFeeCalculator.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 0, 153), new java.awt.Color(0, 0, 153), new java.awt.Color(0, 0, 153), new java.awt.Color(102, 102, 255)));
        btnChangeFeeCalculator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeFeeCalculatorActionPerformed(evt);
            }
        });

        lblChangeCalcInstruction.setText("Change your fee calculator at any time by selecting your choice from the Fee Calculator list and hitting \"Change Fee Calculator\"");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parkinggarage/self-parking-garage1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        btnExitProgram.setBackground(new java.awt.Color(255, 0, 0));
        btnExitProgram.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnExitProgram.setForeground(new java.awt.Color(255, 0, 0));
        btnExitProgram.setText("QUIT");
        btnExitProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitProgramActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblChangeCalcInstruction)
                            .addComponent(lblSelectedCalculator, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxFeeCalculator, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxParkingGarageCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFeeCalculatorHeading)
                                .addGap(71, 71, 71)
                                .addComponent(btnSelectCompanyAndCalculator, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblParkingGarageCompanyHeading)
                            .addComponent(lblSelectedGarage, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnParkCar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblCarParkedStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblHoursParkedHeading)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtHoursParked, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblHoursParkedErrorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(196, 196, 196)
                                .addComponent(lblParkCarsHeading)
                                .addGap(54, 54, 54)
                                .addComponent(btnChangeFeeCalculator, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCheckoutCar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblParkingFee, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExitProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblParkingGarageCompanyHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxParkingGarageCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(lblFeeCalculatorHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSelectCompanyAndCalculator, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jComboBoxFeeCalculator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSelectedGarage, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSelectedCalculator, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblParkCarsHeading, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChangeFeeCalculator, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHoursParkedErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblHoursParkedHeading)
                        .addComponent(txtHoursParked, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnParkCar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblCarParkedStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCheckoutCar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnExitProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblParkingFee, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)))
                .addComponent(lblChangeCalcInstruction, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        lblChangeCalcInstruction.getAccessibleContext().setAccessibleName("Change your fee calculator at ny time by selecting your choice \nfrom the Fee Calculator list ang hitting \"Change Fee Calculator\"");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectCompanyAndCalculatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectCompanyAndCalculatorActionPerformed
        /**
         * This action listener event for the confirm selections button click calls the 
         * confirmSelectedComponents() method.
         * The selected indexes of the JComboBoxes are used to determine the appropriate 
         * file path for the garage totals text file.
         * Labels are used to display the selected garage company, the selected calculator
         * The park car button and change calculator buttons are enabled while the 
         * confirm selections button is disabled.
         */
        ConfirmSelectedComponents();
        
        if(jComboBoxParkingGarageCompany.getSelectedIndex() == 0){
            garageManager.setGarageTotalsFile("src" + File.separatorChar + "parkinggarage" + File.separatorChar + "BestValueGarageTotals.txt");
        }
        if(jComboBoxParkingGarageCompany.getSelectedIndex() == 1){
            garageManager.setGarageTotalsFile("src" + File.separatorChar + "parkinggarage" + File.separatorChar + "ThriftyGarageTotals.txt");
        }
        lblSelectedGarage.setText("You have selected " + parkingCompanyName);
        lblSelectedCalculator.setText("Using " + strategy.toString() + " as your parking calculator");
        btnSelectCompanyAndCalculator.setEnabled(false);
        btnParkCar.setEnabled(true);
        btnChangeFeeCalculator.setEnabled(true);
        
    }//GEN-LAST:event_btnSelectCompanyAndCalculatorActionPerformed

    private void btnParkCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParkCarActionPerformed
        /**
         * This is the action listener event for the park car button click. It disables the 
         * text field where parked hours are entered. It then determines whether the field is blank and also
         * if the entered values are anything other than digits. Any non allowed values will give an error message.
         * If there is a value in the text box it validates that the number entered to make sure it
         * is within the allowed range of parking hours. Finally, the park counter in incremented,
         * a label displays where the car with be parked and for how long, and the parkNewCar() method
         * is delegated to the checkout service object.
         */
        double parkedHours = 0;
        txtHoursParked.setEditable(false);
        
        if(txtHoursParked.getText().length() == MIN_LENGTH){
            lblHoursParkedErrorMessage.setText(HOURS_PARKED_ERROR_MESSAGE);
            txtHoursParked.setEditable(true);
        }
        else{
            try{
            parkedHours = Double.parseDouble(txtHoursParked.getText());
            }
            catch(NumberFormatException nfe){
                JOptionPane.showMessageDialog(rootPane, "Please enter only numbers for parked hours");
                txtHoursParked.setText("");
            }
           
            if(parkedHours <= MIN_PARK_HOURS || parkedHours > MAX_PARK_HOURS ){
            lblHoursParkedErrorMessage.setText(VALID_PARKING_HOURS_ERROR_MESSAGE);
            btnParkCar.setEnabled(true);
            txtHoursParked.setEditable(true);
             
            }
                else{
                    parkCounter+=1;
                    lblHoursParkedErrorMessage.setText("");
                    lblCarParkedStatus.setText("The Car will be parked at " + parkingCompanyName + " for " + parkedHours + " hours." );
                    checkoutService.parkNewCar(parkedHours, parkCounter);
                    btnParkCar.setEnabled(false);
                    btnCheckoutCar.setEnabled(true);
                    }
            }
        
    }//GEN-LAST:event_btnParkCarActionPerformed

    private void btnCheckoutCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckoutCarActionPerformed
        /**
         * This action listener event for the checkout car button creates a new GUIReceiptOutput
         * object for receipt output. It then delegates the checkoutParkedCar() method to the checkout service
         * object. The label are reset and buttons are enabled or disabled accordingly.
         */
        double parkedHours2 = Double.parseDouble(txtHoursParked.getText());
        lblParkingFee.setText("The parking fee accrued is $" + String.valueOf(garageManager.getFeeCalculator().getParkingFee(parkedHours2)));
        
        receiptOutput = ReceiptOutputFactory
            .getInstance()
            .getReceiptOutput(ReceiptOutputFactory.Outputs.GUI);
        
        checkoutService.checkoutParkedCar(parkCounter, parkedHours2, receiptOutput, garageManager);
        lblParkingFee.setText("");
        lblCarParkedStatus.setText("");
        txtHoursParked.setText("");
        btnParkCar.setEnabled(true);
        btnCheckoutCar.setEnabled(false);
        txtHoursParked.setEditable(true);
        
    }//GEN-LAST:event_btnCheckoutCarActionPerformed

    private void btnChangeFeeCalculatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeFeeCalculatorActionPerformed
        /**
         * This action listener event for the change fee calculator button click 
         * gets the selected fee calculator strategy object based on the JComboBox selection
         * and delegates the setParkingFeeCalculationStrategy() method to the garage company
         * object passing the selected strategy object.
         * A label indicates which calculator is currently being used
         */
        
        strategy = (ParkingFeeCalculationStrategy)jComboBoxFeeCalculator.getSelectedItem();
        
        garageCompany.setParkingFeeCalculationStrategy(strategy);
        
        lblSelectedCalculator.setText("Using " + strategy.toString() + " as your parking calculator");
        
    }//GEN-LAST:event_btnChangeFeeCalculatorActionPerformed

    private void btnExitProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitProgramActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitProgramActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangeFeeCalculator;
    private javax.swing.JButton btnCheckoutCar;
    private javax.swing.JButton btnExitProgram;
    private javax.swing.JButton btnParkCar;
    private javax.swing.JButton btnSelectCompanyAndCalculator;
    private javax.swing.JComboBox jComboBoxFeeCalculator;
    private javax.swing.JComboBox jComboBoxParkingGarageCompany;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lblCarParkedStatus;
    private javax.swing.JLabel lblChangeCalcInstruction;
    private javax.swing.JLabel lblFeeCalculatorHeading;
    private javax.swing.JLabel lblHoursParkedErrorMessage;
    private javax.swing.JLabel lblHoursParkedHeading;
    private javax.swing.JLabel lblParkCarsHeading;
    private javax.swing.JLabel lblParkingFee;
    private javax.swing.JLabel lblParkingGarageCompanyHeading;
    private javax.swing.JLabel lblSelectedCalculator;
    private javax.swing.JLabel lblSelectedGarage;
    private javax.swing.JTextField txtHoursParked;
    // End of variables declaration//GEN-END:variables
}
